//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/references.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/tables.tpa"



//Installers.
DEFINE_ACTION_FUNCTION install_vvcs STR_VAR table = "" resources_dir = "" patches = "*" BEGIN
    //Sanitize.
    ACTION_IF NOT ("%patches%" STRING_EQUAL_CASE "*") BEGIN
        ACTION_IF NOT (FILE_EXISTS "%patches%") BEGIN
            FAIL "install_vvcs: patches file '%patches%' does not exist."
        END

        //Include patches file.
        INCLUDE "%patches%"
    END

    ACTION_IF NOT (DIRECTORY_EXISTS "%resources_dir%") BEGIN
        FAIL "install_vvcs: resources directory '%resources_dir%' does not exist."
    END

    //Load table
    LAF load_table STR_VAR
        file = "%table%"
        fields = "resource,install,animation,patch,override,destination"
    RET_ARRAY resources = table END

    //Loop.
    LAF get_table_row_count STR_VAR table = "resources" RET row_count = count END
    OUTER_FOR (i = 0; i < row_count; ++i) BEGIN
        LAF get_row_from_table INT_VAR row = i STR_VAR
            table = "resources"
        RET_ARRAY
            row = array
        END

        WITH_SCOPE BEGIN
            //Inject names in local scope.
            OUTER_TEXT_SPRINT resource $"row"("resource")
            OUTER_TEXT_SPRINT install $"row"("install")
            OUTER_TEXT_SPRINT patch $"row"("patch")
            OUTER_TEXT_SPRINT override $"row"("override")
            OUTER_TEXT_SPRINT destination $"row"("destination")

            ACTION_IF NOT (install = 0) BEGIN
                //Compute destination.
                LAF encode_table_reference STR_VAR
                    value = "%destination%"
                RET destination = return END

                //Sanitize.
                LAF sanitize_resource STR_VAR
                    override = "%override%"
                    destination = "%destination%.vvc"
                    resource = "%resource%"
                END

                COPY "%resources_dir%/%resource%.vvc" "override/%destination%.vvc"
                    PATCH_WITH_SCOPE BEGIN
                        //Inject names in local scope.
                        TEXT_SPRINT animation $"row"("animation")

                        LPF encode_table_reference STR_VAR
                            value = "%animation%"
                        RET animation_res = return END

                        PATCH_IF NOT (FILE_EXISTS_IN_GAME "%animation_res%.bam") BEGIN
                            PATCH_FAIL "install_vvcs: '%animation_res%.bam' for vvc '%resource%' does not exist in game."
                        END
                        
                        LPF set_vvc_field STR_VAR
                            field = "animation"
                            value = "%animation_res%"
                        END
                    END

                    PATCH_IF NOT ("%patch%" STRING_EQUAL_CASE "*") BEGIN
                        LPF "%patch%" STR_VAR destination = "%destination%" END
                    END
            END
        END
    END
END
