//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/references.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/vvcs.tpa"


//Patcher.
DEFINE_PATCH_FUNCTION write_projectile_fields STR_VAR fields = "" BEGIN
    PHP_EACH "%fields%" AS field => value BEGIN
        PATCH_IF ("%field%" STRING_EQUAL_CASE "animation") AND (NOT ("%value%" STRING_EQUAL_CASE "*")) BEGIN
            LPF get_resource_ref STR_VAR
                ref = "%value%"
            RET res = resource END

            PATCH_IF NOT (FILE_EXISTS_IN_GAME "%res%.bam") BEGIN
                PATCH_FAIL "write_projectile_fields: resource '%res%.bam' for animation field does not exist in game."
            END
            
            LPF set_vvc_field STR_VAR
                field = "animation"
                value = "%res%"
            END
        END
    END
END

//Writer.
DEFINE_ACTION_FUNCTION copy_animation STR_VAR
    resource = ""
    dir = ""
    destination = ""
    ext = ""
    patch = "*"
    fields = "*"
BEGIN
    //Source and destination.
    OUTER_TEXT_SPRINT source "%dir%/%resource%.%ext%"
    OUTER_TEXT_SPRINT dest "%destination%.%ext%"

    //Existence checks.
    ACTION_IF NOT (FILE_EXISTS "%source%") BEGIN
        FAIL "copy_animation: source '%source%' of resource '%resource%' does not exist."
    END

    //Copy file.
    COPY "%source%" "override/%dest%"
        LPF write_projectile_fields STR_VAR fields = "%fields%" END

        PATCH_IF NOT ("%patch%" STRING_EQUAL_CASE "*") BEGIN
            LPF "%patch%" STR_VAR
                destination = "%destination%"
            END
        END
END
