//Ids functions.
DEFINE_DIMORPHIC_FUNCTION get_id_from_ids STR_VAR ids = "" value = "" RET id BEGIN
    OUTER_SET id = IDS_OF_SYMBOL ("%ids%" "%value%")
END

DEFINE_DIMORPHIC_FUNCTION get_ids_from_id INT_VAR id = 0 STR_VAR ids = "" RET value BEGIN
    OUTER_PATCH "" BEGIN
        LOOKUP_IDS_SYMBOL_OF_INT value "%ids%" id
    END

    //Normalize.
    ACTION_IF (IS_AN_INT value) BEGIN
        OUTER_TEXT_SPRINT value "*"
    END

    //Avoid casing problems.
    ACTION_TO_LOWER value
END
